### ISSUE TITLE
e.replace is not a function (0.13 => 0.14 break)

### ISSUE THREAD

**Issue by sussdorff** [ferdikoomen/openapi-typescript-codegen#972]
I identified that between 0.13 and 0.14 something was changed which does not validate my openapi.yaml anymore. I verified the validity with swagger validation tools (and it works with version 0.13.0).

Any idea what I should look into (or just stay with 0.13.0)

`Executing command: npx openapi-typescript-codegen --input ./openapi.yaml --output ./sources/openapi  --useOptions
Error: openapi was not generated !
Error: Command failed: npx openapi-typescript-codegen --input ./openapi.yaml --output ./sources/openapi  --useOptions
TypeError: e.replace is not a function
    at Object.<anonymous> (/Users/malte/Sites/webix-kolibri/node_modules/openapi-typescript-codegen/dist/index.js:1:175343)
    at Object.wrapper (/Users/malte/Sites/webix-kolibri/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at 4 (/Users/malte/Sites/webix-kolibri/node_modules/openapi-typescript-codegen/dist/index.js:1:126725)
    at Object.prog [as fn] (/Users/malte/Sites/webix-kolibri/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
    at Object.<anonymous> (/Users/malte/Sites/webix-kolibri/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:29:22)
    at Object.wrapper (/Users/malte/Sites/webix-kolibri/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at 3 (/Users/malte/Sites/webix-kolibri/node_modules/openapi-typescript-codegen/dist/index.js:1:126205)
    at prog (/Users/malte/Sites/webix-kolibri/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
    at execIteration (/Users/malte/Sites/webix-kolibri/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/Users/malte/Sites/webix-kolibri/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npx openapi-typescript-codegen --input ./openapi.yaml --output ./sources/openapi  --useOptions'
}`

**Comment by mstosio** [comment]
I have the same error.

`TypeError: e.replace is not a function
    at Object.<anonymous> ({PATH}/node_modules/openapi-typescript-codegen/dist/index.js:1:183300)
`

**Comment by ferdikoomen** [comment]
@mstosio @sussdorff do you have a spec that is going wrong? And did you try the latest version?

**Comment by sussdorff** [comment]
@ferdikoomen - Sending it over via E-Mail

I tried version 14, 18, 19. None of them work using 
`npx openapi-typescript-codegen --input ./openapi.yaml --output ./sources/openapi  --useOptions`

**Comment by ferdikoomen** [comment]
@sussdorff Thanks!

**Comment by ferdikoomen** [comment]
@sussdorff @mstosio just pushed a new version (v0.20.0) with the fix for this
