### ISSUE TITLE
e.replace is not a function

### ISSUE THREAD

**Issue by slawira** [ferdikoomen/openapi-typescript-codegen#997]
Hello 👋🏼 

I encountered an issue with the latest version `0.20.1` or `0.20.0` which was previous working on version `0.19.0`

```
TypeError: e.replace is not a function
    at /Users/x/Projects/y/node_modules/openapi-typescript-codegen/dist/index.js:1:22367
    at Array.map (<anonymous>)
    at Y (/Users/x/Projects/y/node_modules/openapi-typescript-codegen/dist/index.js:1:22153)
    at z (/Users/x/Projects/y/node_modules/openapi-typescript-codegen/dist/index.js:1:19372)
    at Y (/Users/x/Projects/y/node_modules/openapi-typescript-codegen/dist/index.js:1:24753)
    at Y (/Users/x/Projects/y/node_modules/openapi-typescript-codegen/dist/index.js:1:23566)
    at z (/Users/x/Projects/y/node_modules/openapi-typescript-codegen/dist/index.js:1:19372)
    at Y (/Users/x/Projects/y/node_modules/openapi-typescript-codegen/dist/index.js:1:24753)
    at Y (/Users/x/Projects/y/node_modules/openapi-typescript-codegen/dist/index.js:1:23566)
    at z (/Users/x/Projects/y/node_modules/openapi-typescript-codegen/dist/index.js:1:19372)
```

json input from:
```
https://dash.readme.com/api/v1/api-registry/ddcc1fkydbs0tr
```

if anyone could give me some pointers or could fix this problem, would be awesome! 😄 

Thank you in advance.

**Comment by ferdikoomen** [comment]
The issue is a wrong enum value in some model:
```
"enum":[
	{"override":true},false]
},
```
However, i can add some checks in the parser to ignore this issue

**Comment by ferdikoomen** [comment]
@slawira Just pushed some additional checks to the main branch, will release a new release soon.
