### ISSUE TITLE
Got ReferenceError: Blob is not defined in node v12

### ISSUE THREAD

**Issue by listiani13** [ferdikoomen/openapi-typescript-codegen#879]
**Describe the bug**
Ran into reference error after upgrading from 0.8.1 to 0.11.x in node v12 (node js support `Blob` natively [in >=v15](https://nodejs.org/docs/latest-v15.x/api/buffer.html#buffer_class_blob))

```
 ReferenceError: Blob is not defined
[2021-11-08T15:06:31.311Z]     at isBlob (/usr/src/dist/core/request.js:55:29)
[2021-11-08T15:06:31.311Z]     at getRequestBody (/usr/src/dist/core/request.js:161:44)
```

I think it's introduced here (https://github.com/ferdikoomen/openapi-typescript-codegen/commit/75c335a24ae4aa9a8b67c148f2bd3f0df8867309), when migrating `isBinary` to `isBlob`

Tried importing the `Blob` from `node-fetch`, unfortunately they didn't expose `Blob` constructor

**Comment by ferdikoomen** [comment]
@listiani13 I published a new version 0.12.0-alpha, would you able to retest this? You will need the following dependencies for node JS: https://github.com/ferdikoomen/openapi-typescript-codegen#nodejs-support

**Comment by PanMan** [comment]
The link to https://github.com/ferdikoomen/openapi-typescript-codegen#nodejs-support doesn't work anymore, and I also have Blob issues... (Cannot find name 'Blob'.) in a Nodejs environment.
